name: Packer Validation
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Packer-Validation:
    runs-on: ubuntu-latest
    needs: Integration-Test

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      - name: Packer Init
        run: packer init packer/

      - name: Packer Format
        run: packer fmt packer/

      - name: Packer Validate
        run: packer validate packer/