name: Packer Validation
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Packer-Validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      - name: Packer Init
        run: packer init packer/

      - name: Packer Format
        run: packer fmt -check packer/

      - name: Packer Validate
        env:
            zone: ${{ secrets.PAK_VAR_ZONE }}
            network: ${{ secrets.PAK_VAR_NETWORK }}
            environment: ${{ secrets.PAK_VAR_ENVIRONMENT }}
        run: packer validate -var project_id=${{ secrets.PAK_VAR_PROJECT_ID }} packer/