name: Packer Validation
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Packer-Validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
      
      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Build Application Artifacts
        run: npm run build
      
      - name: Packer Init
        run: packer init packer/

      - name: Packer Format
        run: packer fmt -check packer/

      - name: Packer Validate
        run: |
          packer validate -var project_id=${{ secrets.PAK_VAR_PROJECT_ID }} \
          -var zone=${{ secrets.PAK_VAR_ZONE }} \
          -var network=${{ secrets.PAK_VAR_NETWORK }} \
          -var environment=${{ secrets.PAK_VAR_ENVIRONMENT }} \
          packer/